In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
x =10

In [3]:
x 

10

In [4]:
id(x)

140730453238448

In [5]:
x = '노래가사'

In [6]:
x

'노래가사'

In [7]:
id(x)

2490235414928

In [8]:
[1,2,3,4,5,6,7,8,9,10]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [9]:
type([1,2,3,4,5,6,7,8,9,10])

list

In [10]:
id([1,2,3,4,5,6,7,8,9,10])

2490202548808

In [11]:
import numpy as np

In [12]:
np.array([1,2,3,4,5,6,7,8,9,10])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
type(np.array([1,2,3,4,5,6,7,8,9,10]))

numpy.ndarray

In [14]:
np.array([1,2,3,4,5,6,7,8,9,10]).sum()

55

In [15]:
import pandas as pd

In [16]:
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [17]:
pd.DataFrame(np.linspace(1, 10, 10))

0
0   1.0
1   2.0
2   3.0
3   4.0
4   5.0
5   6.0
6   7.0
7   8.0
8   9.0
9  10.0

In [18]:
pd.DataFrame(np.linspace(1, 10, 10)).sum()

0    55.0
dtype: float64

In [19]:
pd.DataFrame(np.linspace(1, 10, 10)).sum(1)

0     1.0
1     2.0
2     3.0
3     4.0
4     5.0
5     6.0
6     7.0
7     8.0
8     9.0
9    10.0
dtype: float64

# 1부터 n까지 더하기

## 방법 1

In [20]:
1+2+3+4+5+6+7+8+9+10

55

## 방법 2

In [21]:
mylist =[]

for i in range(11):
    mylist.append(i)

In [22]:
mylist

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [23]:
mylist.sum()

AttributeError: 'list' object has no attribute 'sum'

In [24]:
sum(mylist)

55

In [25]:
np.array(mylist)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
np.array(mylist).sum()

55

## 방법3

In [27]:
print([i for i in range(11)])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [28]:
print(np.array([i for i in range(11)]))

[ 0  1  2  3  4  5  6  7  8  9 10]


In [29]:
print(np.array([i for i in range(11)]).sum)

<built-in method sum of numpy.ndarray object at 0x00000243E5D3E8A0>


In [30]:
print(np.array([i for i in range(11)]).sum())

55


In [31]:
np.array([i for i in range(11)]).reshape(2,5)

ValueError: cannot reshape array of size 11 into shape (2,5)

In [32]:
np.array([i for i in range(10)]).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [33]:
np.array([i for i in range(11)]).sum()

55

In [34]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [35]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [36]:
print(np.array([1,2,3,4,5]))

[1 2 3 4 5]


In [37]:
type(print(np.array([1,2,3,4,5])))

[1 2 3 4 5]


NoneType

## 방법4

In [38]:
sum = 0
i = 0
for i in range(10):
    print(i)
    sum =+ i

0
1
2
3
4
5
6
7
8
9


In [39]:
sum

9

In [40]:
sum = 0

for i in range(11):
    print(i)
    sum = sum +i
    print(sum)
    print('*'*100)

0
0
****************************************************************************************************
1
1
****************************************************************************************************
2
3
****************************************************************************************************
3
6
****************************************************************************************************
4
10
****************************************************************************************************
5
15
****************************************************************************************************
6
21
****************************************************************************************************
7
28
****************************************************************************************************
8
36
****************************************************************************************************
9
45
*********************************************

## 방법5

In [41]:
def add(x):
    sum=0
    for i in range(x):
        sum = sum + i 
        
    return sum

In [42]:
add(11)

55

In [43]:
add(100)

4950

In [44]:
add(2000000)

1999999000000

# 짝수만 더할때 - if

In [45]:
sum = 0

for i in range(11):
    if i %2 == 0:
        print(i)
        sum = sum +i

0
2
4
6
8
10


In [46]:
sum

30

In [47]:
[i for i in range(11) if i %2 == 0]

[0, 2, 4, 6, 8, 10]

In [48]:
np.array([i for i in range(11) if i %2 == 0])

array([ 0,  2,  4,  6,  8, 10])

In [49]:
np.array([i for i in range(11) if i %2 == 0]).sum()

30

## 형태가 같은 여러 파일을 합칠 경우

In [51]:
pwd

'd:\\HMOT강의\\scripts'

In [53]:
from glob import glob
glob('*')

['etc',
 'feature engineering',
 'pandas-100-tricks.ipynb',
 'pandas_Groupby Function.ipynb',
 'script_future',
 'script_past',
 'summation_code.ipynb',
 'week_02_pandas groupby love.ipynb',
 'week_02_pandas merge.ipynb',
 'week_02_pandas.ipynb',
 'week_02_pandas_01.ipynb',
 'week_02_pandas_02.ipynb',
 'week_02_pandas_03.ipynb',
 'week_02_pandas_04.ipynb',
 'week_03_03.08-Aggregation-and-Grouping.ipynb',
 'week_03_basic EDA.ipynb',
 'week_03_case by case 01_이상치탐색.ipynb',
 'week_03_case by case 02_이상치탐색(가우시안프로세스).ipynb',
 'week_03_case by case 03_monte_carlo.ipynb',
 'week_03_case by case 04_통계적 추론.ipynb',
 'week_03_case by case 05_text mining.ipynb',
 'week_03_pandas merge.ipynb',
 'week_03_statistics_01.ipynb',
 'week_03_statistics_02.ipynb',
 'week_03_statistics_03.ipynb',
 'whirlwind',
 '__pycache__']

In [58]:
glob('../data/*자전거*.*')

['../data\\2015년_자전거사고다발지.csv',
 '../data\\2016년_자전거사고다발지.csv',
 '../data\\2017년_자전거사고다발지.csv']

In [63]:
for i in glob('../data/*자전거*.*'):
    i
    i.split('\\')
    i.split('\\')[1]
    i.split('\\')[1].split('.')[0]

'../data\\2015년_자전거사고다발지.csv'

['../data', '2015년_자전거사고다발지.csv']

'2015년_자전거사고다발지.csv'

'2015년_자전거사고다발지'

'../data\\2016년_자전거사고다발지.csv'

['../data', '2016년_자전거사고다발지.csv']

'2016년_자전거사고다발지.csv'

'2016년_자전거사고다발지'

'../data\\2017년_자전거사고다발지.csv'

['../data', '2017년_자전거사고다발지.csv']

'2017년_자전거사고다발지.csv'

'2017년_자전거사고다발지'

In [71]:
for i in glob('../data/*자전거*.*'):
    pd.read_csv(i, encoding='euc-kr').head()
    pd.read_csv(i, encoding='euc-kr').shape

다발지식별자  다발지그룹식별자       법정동코드      스팟코드        관할경찰서  \
0  6193264   2016047  1121510500  11215011  서울특별시 광진구11   
1  6193269   2016047  1121510500  11215012  서울특별시 광진구12   
2  6176261   2016047  1121510300  11215013  서울특별시 광진구13   
3  6193267   2016047  1121510400  11215014  서울특별시 광진구14   
4  6176982   2016047  1121510300  11215015  서울특별시 광진구15   

                                 다발지명  발생건수  사상자수  사망자수  중상자수  경상자수  부상신고자수  \
0            서울특별시 광진구 자양동(신자초교입구 부근)     4     4     0     3     1       0   
1  서울특별시 광진구 자양동(동부간선도로-강변북로램프(4) 부근)     4     4     0     3     1       0   
2          서울특별시 광진구 구의동(어린이대공원후문 부근)     4     4     0     3     1       0   
3             서울특별시 광진구 광장동(광장사거리 부근)     4     4     0     3     1       0   
4    서울특별시 광진구 구의동(강변북로-광나룻길램프(4) 부근)     4     4     0     1     2       1   

           경도         위도                                            다발지역폴리곤  
0  127.076086  37.534282  { "type": "Polygon", "coordinates": [ [ [ 128....  
1  127.064597  37.529759  { "type": "Polygon", "coordinates": [ [ [ 126....  
2  127.090115  37.551393  { "type": "Polygon", "coordinates": [ [ [ 129....  
3  127.103341  37.545383  { "type": "Polygon", "coordinates": [ [ [ 128....  
4  127.098297  37.539388  { "type": "Polygon", "coordinates": [ [ [ 127....

(597, 15)

다발지식별자  다발지그룹식별자       법정동코드      스팟코드          관할경찰서  \
0  6302989   2017050  4729010900  47290002      경상북도 경산시2   
1  6319031   2017050  4311110100  43111002  충청북도 청주시 상당구2   
2  6315518   2017050  2720010200  27200001      대구광역시 남구1   
3  6315519   2017050  2720010300  27200002      대구광역시 남구2   
4  6315828   2017050  2723010100  27230005      대구광역시 북구5   

                             다발지명  발생건수  사상자수  사망자수  중상자수  경상자수  부상신고자수  \
0           경상북도 경산시 옥산동(카페벙커 부근)     4     4     0     2     1       1   
1       충청북도 청주시 상당구 영동(파리바게트 부근)     4     4     1     2     0       1   
2          대구광역시 남구 봉덕동(영대네거리 부근)     6     6     0     2     2       2   
3  대구광역시 남구 대명동(+갓바위 산골 순두부보쌈 부근)     4     4     0     2     0       2   
4         대구광역시 북구 칠성동1가(금강장어 부근)     6     6     0     2     4       0   

           경도         위도                                            다발지역폴리곤  
0  128.729484  35.824647  {"type":"Polygon","coordinates":[[[128.7316980...  
1  127.487318  36.636664  {"type":"Polygon","coordinates":[[[127.4895554...  
2  128.590625  35.845414  {"type":"Polygon","coordinates":[[[128.5928396...  
3  128.590535  35.853810  {"type":"Polygon","coordinates":[[[128.5927492...  
4  128.602507  35.876505  {"type":"Polygon","coordinates":[[[128.6047219...

(492, 15)

다발지식별자  다발지그룹식별자       법정동코드      스팟코드       관할경찰서  \
0  6411461   2018032  1130510300  11305001  서울특별시 강북구1   
1  6411839   2018032  1130510300  11305002  서울특별시 강북구2   
2  6411840   2018032  1130510200  11305003  서울특별시 강북구3   
3  6411836   2018032  1130510100  11305004  서울특별시 강북구4   
4  6411835   2018032  1130510300  11305005  서울특별시 강북구5   

                              다발지명  발생건수  사상자수  사망자수  중상자수  경상자수  부상신고자수  \
0          서울특별시 강북구 수유동(수유사거리 부근)     6     6     0     3     3       0   
1           서울특별시 강북구 수유동(선아트빌 부근)     6     7     0     1     6       0   
2       서울특별시 강북구 번동(모아한의원 수유점 부근)     5     6     0     0     6       0   
3  서울특별시 강북구 미아동(한국전력공사 강북성북지사 부근)     5     5     0     0     4       1   
4         서울특별시 강북구 수유동(한신대사거리 부근)     4     7     0     3     4       0   

           경도         위도                                            다발지역폴리곤  
0  127.024359  37.635531  {"type":"Polygon","coordinates":[[[127.0266252...  
1  127.010603  37.645888  {"type":"Polygon","coordinates":[[[127.0128703...  
2  127.031468  37.635410  {"type":"Polygon","coordinates":[[[127.0337346...  
3  127.024925  37.630355  {"type":"Polygon","coordinates":[[[127.0271910...  
4  127.015626  37.634032  {"type":"Polygon","coordinates":[[[127.0178929...

(386, 15)

## 데이터프레임을 계속 쌓는다

In [69]:
df =pd.DataFrame()
for i in glob('../data/*자전거*.*'):
    df = df.append(pd.read_csv(i, encoding='euc-kr'))

In [70]:
df.shape

(1475, 15)

In [72]:
dir_path = 'D:/HMOT강의/output/'
df.to_csv(dir_path + '자전거.csv')

In [73]:
%time pd.read_csv(dir_path + '자전거.csv')

Wall time: 34.9 ms


Unnamed: 0   다발지식별자  다발지그룹식별자       법정동코드      스팟코드        관할경찰서  \
0              0  6193264   2016047  1121510500  11215011  서울특별시 광진구11   
1              1  6193269   2016047  1121510500  11215012  서울특별시 광진구12   
2              2  6176261   2016047  1121510300  11215013  서울특별시 광진구13   
3              3  6193267   2016047  1121510400  11215014  서울특별시 광진구14   
4              4  6176982   2016047  1121510300  11215015  서울특별시 광진구15   
...          ...      ...       ...         ...       ...          ...   
1470         381  6411408   2018032  3114010100  31140002    울산광역시 남구2   
1471         382  6412798   2018032  3114010400  31140003    울산광역시 남구3   
1472         383  6411434   2018032  2723012600  27230012   대구광역시 북구12   
1473         384  6411769   2018032  2723012400  27230013   대구광역시 북구13   
1474         385  6411214   2018032  2723011000  27230014   대구광역시 북구14   

                                    다발지명  발생건수  사상자수  사망자수  중상자수  경상자수  \
0               서울특별시 광진구 자양동(신자초교입구 부근)     4     4     0     3     1   
1     서울특별시 광진구 자양동(동부간선도로-강변북로램프(4) 부근)     4     4     0     3     1   
2             서울특별시 광진구 구의동(어린이대공원후문 부근)     4     4     0     3     1   
3                서울특별시 광진구 광장동(광장사거리 부근)     4     4     0     3     1   
4       서울특별시 광진구 구의동(강변북로-광나룻길램프(4) 부근)     4     4     0     1     2   
...                                  ...   ...   ...   ...   ...   ...   
1470              울산광역시 남구 무거동(신복로터리 부근)     4     4     0     2     2   
1471               울산광역시 남구 신정동(신정공원 부근)     4     4     0     0     4   
1472              대구광역시 북구 태전동(태전삼거리 부근)     5     6     0     1     4   
1473     대구광역시 북구 동천동(ABC마트 ST 대구칠곡점 부근)     5     6     0     1     4   
1474             대구광역시 북구 대현동(경대교사거리 부근)     4     4     0     2     2   

      부상신고자수          경도         위도  \
0          0  127.076086  37.534282   
1          0  127.064597  37.529759   
2          0  127.090115  37.551393   
3          0  127.103341  37.545383   
4          1  127.098297  37.539388   
...      ...         ...        ...   
1470       0  129.263182  35.549777   
1471       0  129.316606  35.548264   
1472       1  128.546768  35.919590   
1473       1  128.560578  35.942891   
1474       0  128.602258  35.886520   

                                                다발지역폴리곤  
0     { "type": "Polygon", "coordinates": [ [ [ 128....  
1     { "type": "Polygon", "coordinates": [ [ [ 126....  
2     { "type": "Polygon", "coordinates": [ [ [ 129....  
3     { "type": "Polygon", "coordinates": [ [ [ 128....  
4     { "type": "Polygon", "coordinates": [ [ [ 127....  
...                                                 ...  
1470  {"type":"Polygon","coordinates":[[[129.2653878...  
1471  {"type":"Polygon","coordinates":[[[129.3188113...  
1472  {"type":"Polygon","coordinates":[[[128.5489839...  
1473  {"type":"Polygon","coordinates":[[[128.5627955...  
1474  {"type":"Polygon","coordinates":[[[128.6044739...  

[1475 rows x 16 columns]

## pickle : 압축형태 판다 파일, 대용량 데이터 처리

In [77]:
df.to_pickle(dir_path + '자전거.pkl')

In [78]:
%time pd.read_pickle(dir_path + '자전거.pkl')

Wall time: 6.98 ms


다발지식별자  다발지그룹식별자       법정동코드      스팟코드        관할경찰서  \
0    6193264   2016047  1121510500  11215011  서울특별시 광진구11   
1    6193269   2016047  1121510500  11215012  서울특별시 광진구12   
2    6176261   2016047  1121510300  11215013  서울특별시 광진구13   
3    6193267   2016047  1121510400  11215014  서울특별시 광진구14   
4    6176982   2016047  1121510300  11215015  서울특별시 광진구15   
..       ...       ...         ...       ...          ...   
381  6411408   2018032  3114010100  31140002    울산광역시 남구2   
382  6412798   2018032  3114010400  31140003    울산광역시 남구3   
383  6411434   2018032  2723012600  27230012   대구광역시 북구12   
384  6411769   2018032  2723012400  27230013   대구광역시 북구13   
385  6411214   2018032  2723011000  27230014   대구광역시 북구14   

                                   다발지명  발생건수  사상자수  사망자수  중상자수  경상자수  부상신고자수  \
0              서울특별시 광진구 자양동(신자초교입구 부근)     4     4     0     3     1       0   
1    서울특별시 광진구 자양동(동부간선도로-강변북로램프(4) 부근)     4     4     0     3     1       0   
2            서울특별시 광진구 구의동(어린이대공원후문 부근)     4     4     0     3     1       0   
3               서울특별시 광진구 광장동(광장사거리 부근)     4     4     0     3     1       0   
4      서울특별시 광진구 구의동(강변북로-광나룻길램프(4) 부근)     4     4     0     1     2       1   
..                                  ...   ...   ...   ...   ...   ...     ...   
381              울산광역시 남구 무거동(신복로터리 부근)     4     4     0     2     2       0   
382               울산광역시 남구 신정동(신정공원 부근)     4     4     0     0     4       0   
383              대구광역시 북구 태전동(태전삼거리 부근)     5     6     0     1     4       1   
384     대구광역시 북구 동천동(ABC마트 ST 대구칠곡점 부근)     5     6     0     1     4       1   
385             대구광역시 북구 대현동(경대교사거리 부근)     4     4     0     2     2       0   

             경도         위도                                            다발지역폴리곤  
0    127.076086  37.534282  { "type": "Polygon", "coordinates": [ [ [ 128....  
1    127.064597  37.529759  { "type": "Polygon", "coordinates": [ [ [ 126....  
2    127.090115  37.551393  { "type": "Polygon", "coordinates": [ [ [ 129....  
3    127.103341  37.545383  { "type": "Polygon", "coordinates": [ [ [ 128....  
4    127.098297  37.539388  { "type": "Polygon", "coordinates": [ [ [ 127....  
..          ...        ...                                                ...  
381  129.263182  35.549777  {"type":"Polygon","coordinates":[[[129.2653878...  
382  129.316606  35.548264  {"type":"Polygon","coordinates":[[[129.3188113...  
383  128.546768  35.919590  {"type":"Polygon","coordinates":[[[128.5489839...  
384  128.560578  35.942891  {"type":"Polygon","coordinates":[[[128.5627955...  
385  128.602258  35.886520  {"type":"Polygon","coordinates":[[[128.6044739...  

[1475 rows x 15 columns]

# End