# week_03 일차 파이썬 프로그래밍

## 2.2 Numpy와 Pandas

In [1]:
import numpy as np

In [2]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

## A Python List is more than just a list
list is the standard mutable multielement(heterogeneous) container in Python.

In [13]:
list(range(10))
np.array(range(0,10))
np.arange(10)
np.arange(0,10,2)
list(np.arange(0,10,2))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([0, 2, 4, 6, 8])

[0, 2, 4, 6, 8]

In [14]:
l = list(range(10))
l
l_2 = [str(c) for c in l]
l_2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [15]:
l_3 = [True, '2', 3.4, 5]
[type(c) for c in l_3]

[bool, str, float, int]

object

In [16]:
%timeit np.arange(1000, dtype='int64').sum()

3.41 µs ± 109 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [17]:
%timeit np.arange(1000, dtype='object').sum()

28.7 µs ± 3 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


### Numpy

In [18]:
v = np.array([-1, 2])
A = np.array([[3,1], [1,2]])
v
A
np.dot(v, A)
np.dot(A, v)

array([-1,  2])

array([[3, 1],
       [1, 2]])

array([-1,  3])

array([-1,  3])

broadcasting calculation - row wise

In [19]:
A.shape
v.shape
A*v
v*A

(2, 2)

(2,)

array([[-3,  2],
       [-1,  4]])

array([[-3,  2],
       [-1,  4]])

broadcasting calculation - columns wise

In [20]:
A.shape
v.reshape(-1,1).shape
A
v
A*v.reshape(-1,1)

(2, 2)

(2, 1)

array([[3, 1],
       [1, 2]])

array([-1,  2])

array([[-3, -1],
       [ 2,  4]])

In [21]:
a = np.array([[2,-1], [-1,2]])
a
b = np.array([0,3])
b
a.shape
b.shape

array([[ 2, -1],
       [-1,  2]])

array([0, 3])

(2, 2)

(2,)

In [22]:
np.linalg.inv(a)@a
np.linalg.inv(a)@b

array([[1., 0.],
       [0., 1.]])

array([1., 2.])

In [23]:
np.array([2,4,6]) # 1차원
np.array([2,4,6]).shape

array([2, 4, 6])

(3,)

In [24]:
a= np.random.randn(5)
a
a.shape

array([ 1.78821292,  1.90255763, -1.67814815, -0.25315215,  1.06273406])

(5,)

In [25]:
a.T

array([ 1.78821292,  1.90255763, -1.67814815, -0.25315215,  1.06273406])

In [26]:
a= np.random.randn(5,1)
a
a.shape

array([[-0.75949237],
       [-1.06683391],
       [ 0.9323552 ],
       [-1.3171375 ],
       [-1.08011285]])

(5, 1)

In [27]:
np.array([range(i, i+3) for i in [2,4,6]]) # 2차원은 numpy로 가능, 고차원 표시도 가능
np.array([range(i, i+3) for i in [2,4,6]]).shape

np.array([[range(i, i+3) for i in [2,4,6]]])
np.array([[range(i, i+3) for i in [2,4,6]]]).shape

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

(3, 3)

array([[[2, 3, 4],
        [4, 5, 6],
        [6, 7, 8]]])

(1, 3, 3)

In [28]:
np.array([2,4,6])
list(np.array([2,4,6]))
np.array([2,4,6]).tolist()

array([2, 4, 6])

[2, 4, 6]

[2, 4, 6]

In [29]:
np.random.randint(10, size=(3, 3, 3))

array([[[6, 0, 0],
        [3, 6, 9],
        [2, 6, 5]],

       [[8, 2, 4],
        [5, 2, 1],
        [7, 1, 6]],

       [[3, 7, 4],
        [4, 9, 6],
        [6, 6, 9]]])

In [30]:
np.arange(10)
np.arange(0, 20, 2)
np.hstack([np.arange(10), np.arange(0, 20, 2)])
np.vstack([np.arange(10), np.arange(0, 20, 2)])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,  0,  2,  4,  6,  8, 10, 12,
       14, 16, 18])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18]])

In [31]:
%time s = sum([i for i in range(1,99999)])

%time s = np.arange(99999).sum()

Wall time: 8 ms
Wall time: 2.13 ms


In [32]:
np.random.seed(1357)
m = np.random.randint(1,100,12)
m

m.max()
m.min()
m.sum()
m.mean()
m.std()

array([52, 71, 72, 80, 72, 53, 71, 46, 68, 59, 55, 19])

80

19

718

59.833333333333336

15.836841716565697

In [33]:
m.argmin() 
m.argmax()
m.argsort()
np.argsort(-m)

11

3

array([11,  7,  0,  5, 10,  9,  8,  1,  6,  2,  4,  3], dtype=int64)

array([ 3,  2,  4,  1,  6,  8,  9, 10,  5,  0,  7, 11], dtype=int64)

In [34]:
m
m.shape # vector
m.reshape(-1,1).shape # matrix

array([52, 71, 72, 80, 72, 53, 71, 46, 68, 59, 55, 19])

(12,)

(12, 1)

In [35]:
mr = m.reshape(3,4)
mr

array([[52, 71, 72, 80],
       [72, 53, 71, 46],
       [68, 59, 55, 19]])

In [36]:
x = np.array([1,2,3])
x
x.shape
x.reshape(1,3)
x[np.newaxis, :]

array([1, 2, 3])

(3,)

array([[1, 2, 3]])

array([[1, 2, 3]])

In [37]:
x.reshape(3,1)
x[:, np.newaxis]
x[:, np.newaxis].shape

array([[1],
       [2],
       [3]])

array([[1],
       [2],
       [3]])

(3, 1)

In [38]:
mr[:, np.newaxis, :]
mr[:, np.newaxis, :].shape

array([[[52, 71, 72, 80]],

       [[72, 53, 71, 46]],

       [[68, 59, 55, 19]]])

(3, 1, 4)

In [39]:
mr[np.newaxis, :]
mr[np.newaxis, :].shape

mr[:, np.newaxis]
mr[:, np.newaxis].shape

array([[[52, 71, 72, 80],
        [72, 53, 71, 46],
        [68, 59, 55, 19]]])

(1, 3, 4)

array([[[52, 71, 72, 80]],

       [[72, 53, 71, 46]],

       [[68, 59, 55, 19]]])

(3, 1, 4)

In [40]:
mr[2][3]
mr[0:2] 
mr[:, [1,2]]
mr[:, 0:3]
mr[:2, 2:]

19

array([[52, 71, 72, 80],
       [72, 53, 71, 46]])

array([[71, 72],
       [53, 71],
       [59, 55]])

array([[52, 71, 72],
       [72, 53, 71],
       [68, 59, 55]])

array([[72, 80],
       [71, 46]])

In [41]:
mr

array([[52, 71, 72, 80],
       [72, 53, 71, 46],
       [68, 59, 55, 19]])

In [42]:
mr> 70

array([[False,  True,  True,  True],
       [ True, False,  True, False],
       [False, False, False, False]])

In [43]:
mr[mr> 70]

array([71, 72, 80, 72, 71])

In [44]:
np.sum(mr > 75)

1

In [45]:
mr[2, [0,2]]

array([68, 55])

### 연산

In [46]:
x = np.arange(12).reshape((4,3))
x

y = np.array(range(12,0,-1)).reshape((4,3))
y

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

array([[12, 11, 10],
       [ 9,  8,  7],
       [ 6,  5,  4],
       [ 3,  2,  1]])

In [47]:
x+y

array([[12, 12, 12],
       [12, 12, 12],
       [12, 12, 12],
       [12, 12, 12]])

In [48]:
x-y

array([[-12, -10,  -8],
       [ -6,  -4,  -2],
       [  0,   2,   4],
       [  6,   8,  10]])

In [49]:
x*y

array([[ 0, 11, 20],
       [27, 32, 35],
       [36, 35, 32],
       [27, 20, 11]])

In [50]:
y = np.array(range(12,0,-1)).reshape((3,4))
y

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [51]:
x.dot(y)

array([[ 16,  13,  10,   7],
       [ 88,  76,  64,  52],
       [160, 139, 118,  97],
       [232, 202, 172, 142]])

In [52]:
np.dot(x,y)

array([[ 16,  13,  10,   7],
       [ 88,  76,  64,  52],
       [160, 139, 118,  97],
       [232, 202, 172, 142]])

In [53]:
x@y

array([[ 16,  13,  10,   7],
       [ 88,  76,  64,  52],
       [160, 139, 118,  97],
       [232, 202, 172, 142]])

## <font color='red'> 실습숙제 :  분산과 공분산

In [54]:
from sklearn.datasets import load_iris
data = load_iris()
data

ModuleNotFoundError: No module named 'sklearn'

In [55]:
type(data)
data.keys()

NameError: name 'data' is not defined

In [112]:
data.feature_names
data.target_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [113]:
data.data.shape
data.data[0:10]
data.target[0:10]
data.target.shape

(150, 4)

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

(150,)

In [114]:
features = data.data

### (1) features 공분산/상관관계 구하기

In [115]:
np.cov(features.T)

array([[ 0.68569351, -0.042434  ,  1.27431544,  0.51627069],
       [-0.042434  ,  0.18997942, -0.32965638, -0.12163937],
       [ 1.27431544, -0.32965638,  3.11627785,  1.2956094 ],
       [ 0.51627069, -0.12163937,  1.2956094 ,  0.58100626]])

In [116]:
np.corrcoef(features.T)

array([[ 1.        , -0.11756978,  0.87175378,  0.81794113],
       [-0.11756978,  1.        , -0.4284401 , -0.36612593],
       [ 0.87175378, -0.4284401 ,  1.        ,  0.96286543],
       [ 0.81794113, -0.36612593,  0.96286543,  1.        ]])

### (2) mean centering한 features 공분산/상관관계 구하기

In [117]:
np.mean(features, axis=0)
np.std(features, axis=0)
x_standard = (features - np.mean(features, axis=0)) / np.std(features, axis=0)
np.mean(x_standard, axis=0)
np.std(x_standard, axis=0)

array([5.84333333, 3.05733333, 3.758     , 1.19933333])

array([0.82530129, 0.43441097, 1.75940407, 0.75969263])

array([-1.69031455e-15, -1.84297022e-15, -1.69864123e-15, -1.40924309e-15])

array([1., 1., 1., 1.])

In [118]:
np.cov(x_standard.T)

array([[ 1.00671141, -0.11835884,  0.87760447,  0.82343066],
       [-0.11835884,  1.00671141, -0.43131554, -0.36858315],
       [ 0.87760447, -0.43131554,  1.00671141,  0.96932762],
       [ 0.82343066, -0.36858315,  0.96932762,  1.00671141]])

In [119]:
np.corrcoef(x_standard.T)

array([[ 1.        , -0.11756978,  0.87175378,  0.81794113],
       [-0.11756978,  1.        , -0.4284401 , -0.36612593],
       [ 0.87175378, -0.4284401 ,  1.        ,  0.96286543],
       [ 0.81794113, -0.36612593,  0.96286543,  1.        ]])

### (3) features와 target 상관관계 구하기

In [120]:
np.corrcoef(features.T, data.target)

array([[ 1.        , -0.11756978,  0.87175378,  0.81794113,  0.78256123],
       [-0.11756978,  1.        , -0.4284401 , -0.36612593, -0.42665756],
       [ 0.87175378, -0.4284401 ,  1.        ,  0.96286543,  0.9490347 ],
       [ 0.81794113, -0.36612593,  0.96286543,  1.        ,  0.95654733],
       [ 0.78256123, -0.42665756,  0.9490347 ,  0.95654733,  1.        ]])

In [121]:
iris_data = np.hstack([data.data, data.target.reshape(-1,1)])

In [122]:
np.corrcoef(iris_data.T)

array([[ 1.        , -0.11756978,  0.87175378,  0.81794113,  0.78256123],
       [-0.11756978,  1.        , -0.4284401 , -0.36612593, -0.42665756],
       [ 0.87175378, -0.4284401 ,  1.        ,  0.96286543,  0.9490347 ],
       [ 0.81794113, -0.36612593,  0.96286543,  1.        ,  0.95654733],
       [ 0.78256123, -0.42665756,  0.9490347 ,  0.95654733,  1.        ]])

In [152]:
data.feature_names.append('class')

In [128]:
import pandas as pd
dir_path ='D:/대학강의/data/'
df = pd.DataFrame(data.data, columns = data.feature_names)
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [130]:
df['calss'] = data.target
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     calss  
0        0  
1        0  
2        0  
3        0  
4        0  
..     ...  
145      2  
146      2  
147      2  
148      2  
149      2  

[150 rows x 5 columns]

In [157]:
df.to_excel(dir_path + '실습01.xlsx')
df.corr()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
sepal length (cm)           1.000000         -0.117570           0.871754   
sepal width (cm)           -0.117570          1.000000          -0.428440   
petal length (cm)           0.871754         -0.428440           1.000000   
petal width (cm)            0.817941         -0.366126           0.962865   
class                       0.782561         -0.426658           0.949035   

                   petal width (cm)     class  
sepal length (cm)          0.817941  0.782561  
sepal width (cm)          -0.366126 -0.426658  
petal length (cm)          0.962865  0.949035  
petal width (cm)           1.000000  0.956547  
class                      0.956547  1.000000

## Pandas

In [131]:
import pandas as pd
data = m.reshape((3,4))
pd.DataFrame(data)

0   1   2   3
0  52  71  72  80
1  72  53  71  46
2  68  59  55  19

In [132]:
type(data)

numpy.ndarray

In [133]:
data

array([[52, 71, 72, 80],
       [72, 53, 71, 46],
       [68, 59, 55, 19]])

In [134]:
index = range(1,4)
columns = ['A','B','C','D']
df = pd.DataFrame(data, index = index, columns = columns)
df

A   B   C   D
1  52  71  72  80
2  72  53  71  46
3  68  59  55  19

In [135]:
df.loc[2]
df.iloc[1]
df.loc[2, 'B']
df.iloc[1, 1]

A    72
B    53
C    71
D    46
Name: 2, dtype: int32

A    72
B    53
C    71
D    46
Name: 2, dtype: int32

53

53

In [136]:
df['A']
type(df['A'])
df[['A','B']]
type(df[['A','B']])
df[['A','B']].loc[2]

1    52
2    72
3    68
Name: A, dtype: int32

pandas.core.series.Series

A   B
1  52  71
2  72  53
3  68  59

pandas.core.frame.DataFrame

A    72
B    53
Name: 2, dtype: int32

In [137]:
df[1:]
df[-1:]

A   B   C   D
2  72  53  71  46
3  68  59  55  19

A   B   C   D
3  68  59  55  19

In [138]:
df['A']
df.A

1    52
2    72
3    68
Name: A, dtype: int32

1    52
2    72
3    68
Name: A, dtype: int32

In [139]:
df>=60
df[df>=60]
np.array(df>=60)*1 # (df>=60).values*1
pd.DataFrame(np.array(df>=60)*1, index = index, columns = columns)

A      B      C      D
1  False   True   True   True
2   True  False   True  False
3   True  False  False  False

A     B     C     D
1   NaN  71.0  72.0  80.0
2  72.0   NaN  71.0   NaN
3  68.0   NaN   NaN   NaN

array([[0, 1, 1, 1],
       [1, 0, 1, 0],
       [1, 0, 0, 0]])

A  B  C  D
1  0  1  1  1
2  1  0  1  0
3  1  0  0  0

In [140]:
df[df['C']>60]
df[(df['B']>50)&(df['C']<70)]

A   B   C   D
1  52  71  72  80
2  72  53  71  46

A   B   C   D
3  68  59  55  19

In [141]:
df = df[df>60].copy()
df['E'] = ['owl', 'fox', 'owl']
df
df.isnull().sum()
df.nunique()
df.dtypes

A     B     C     D    E
1   NaN  71.0  72.0  80.0  owl
2  72.0   NaN  71.0   NaN  fox
3  68.0   NaN   NaN   NaN  owl

A    1
B    2
C    1
D    2
E    0
dtype: int64

A    2
B    1
C    2
D    1
E    2
dtype: int64

A    float64
B    float64
C    float64
D    float64
E     object
dtype: object

In [142]:
type(df.isnull().sum()); df.isnull().sum().shape
type(df.nunique()); df.nunique().shape
type(df.dtypes); df.dtypes.shape

pandas.core.series.Series

(5,)

pandas.core.series.Series

(5,)

pandas.core.series.Series

(5,)

In [143]:
df.fillna(0)
df.fillna(0, inplace = True)  # df = df.fillna(0)
df

A     B     C     D    E
1   0.0  71.0  72.0  80.0  owl
2  72.0   0.0  71.0   0.0  fox
3  68.0   0.0   0.0   0.0  owl

A     B     C     D    E
1   0.0  71.0  72.0  80.0  owl
2  72.0   0.0  71.0   0.0  fox
3  68.0   0.0   0.0   0.0  owl

In [144]:
df = pd.DataFrame(mr, index = [i for i in 'abc'], columns = ['A','B','C','D'])
df
df.drop('c')
df.drop(['a', 'c'])

A   B   C   D
a  52  71  72  80
b  72  53  71  46
c  68  59  55  19

A   B   C   D
a  52  71  72  80
b  72  53  71  46

A   B   C   D
b  72  53  71  46

In [145]:
df.drop('C', axis=1)
df.drop(['A', 'C'], axis=1)

A   B   D
a  52  71  80
b  72  53  46
c  68  59  19

B   D
a  71  80
b  53  46
c  59  19

In [146]:
df.loc['d'] = df.loc['b']
df
df.duplicated()
df[~df.duplicated()]

A   B   C   D
a  52  71  72  80
b  72  53  71  46
c  68  59  55  19
d  72  53  71  46

a    False
b    False
c    False
d     True
dtype: bool

A   B   C   D
a  52  71  72  80
b  72  53  71  46
c  68  59  55  19

In [147]:
print(type('hello'))
print(type(sum([1,2,3])))

<class 'str'>
<class 'int'>


In [148]:
def summary(df) :
    tf = pd.DataFrame({'데이터형태(dtypes)' : df.dtypes,
                       '결측치 수(null)' : df.isnull().sum(),
                       '고유값 수(nunique)' : df.nunique()})
    return tf

print(type(summary(df)))
summary(df)

<class 'pandas.core.frame.DataFrame'>


데이터형태(dtypes)  결측치 수(null)  고유값 수(nunique)
A         int32            0               3
B         int32            0               3
C         int32            0               3
D         int32            0               3

In [149]:
def test_var_args(f_arg, *argv):
    print("first normal arg:", f_arg)
    for arg in argv:
        print("another arg through *argv:", arg)

test_var_args('sanggoo', 'python', 'eggs', 'apple')

first normal arg: sanggoo
another arg through *argv: python
another arg through *argv: eggs
another arg through *argv: apple


In [150]:
def greet_me(**kwargs):
    for key, value in kwargs.items():
        print("{0} = {1}".format(key, value))
        
greet_me(name="sanggoo", fruit ="apple")

name = sanggoo
fruit = apple


In [151]:
def add(x, y, z=1) :
    return (x + y + z)
add(10, 20, z=50)

80

In [152]:
def display(add, *arg, **kwargs) :
    print(arg)
    print(kwargs)
    print(add)
    
    return add(*arg, **kwargs)

In [153]:
display(add, 10, 20, z=50)

(10, 20)
{'z': 50}
<function add at 0x00000125ECBB4048>


80

In [154]:
print(type(1.0))
print(type('hello'))

<class 'float'>
<class 'str'>


In [155]:
class Member:
    def name():
        print('모른다')
        
    def age():
        print('알거없다')

In [156]:
m = Member()
print(type(m))

<class '__main__.Member'>


In [157]:
m.name()

TypeError: name() takes 0 positional arguments but 1 was given

In [158]:
class Member:
    def name(a):
        print('모른다')
        
    def age():
        print('알거없다')

In [159]:
m = Member()
m.name()
m.grade()

모른다


AttributeError: 'Member' object has no attribute 'grade'

In [160]:
class Member:
    def __init__(self, name, age):
        self.name = name
        self.age = age    
        
    def get_name(self):
        return self.name      
    
    def get_age(self):
        return self.age
    
    def set_age(self, age):
        self.age = age

In [161]:
m = Member('홍길동', 23)
m.get_name()
m.get_age()

'홍길동'

23

In [162]:
m.set_age(33)
m.name
m.age
m.get_age()

'홍길동'

33

33

In [163]:
class Student:
    def __init__(self, name, age, grade):
        self.name = name
        self.age = age
        self.grade = grade
        
    def get_grade(self):
        return self.grade 

    def show(self):
        print(f'내 이름은 {self.name}, {self.age}살 이야.') 

class Course:
    def __init__(self, name, max_students) :
        self.name = name
        self.max_students = max_students
        self.students = []
        self.is_active = False
        
    def add_student(self, student):
        print(student)
        if len(self.students) < self.max_students:
            self.students.append(student)
            return '수강신청 완료'
        return '최대인원 초과로 수강신청 불가'
    
    def get_average_grade(self):
        value = 0
        for student in self.students:
            value += student.get_grade()
        return value/len(self.students)

In [164]:
s1 = Student('Tim', 19, 95)
s2 = Student('Bill', 19, 75)
s3 = Student('Jill', 19, 65)

In [165]:
course =Course('Science', 2)
course
course.add_student(s1)
course.add_student(s2)

'수강신청 완료'

'수강신청 완료'

In [166]:
print(type(course.students))
course.students
print(course.students[0])
print(course.students[0].name)

<class 'list'>


[<__main__.Student at 0x125ecbd2d88>, <__main__.Student at 0x125ecbd2d08>]

Tim


In [167]:
course.add_student(s3)
print(course.get_average_grade())

'최대인원 초과로 수강신청 불가'

85.0


In [168]:
class Female(Student):
    def speak(self):
        print('어머나 어머나')
        
class Male(Student):
    def speak(self):
        print('아이쿠 아이쿠')

In [169]:
f = Female('Eve', 16, 75) 
f.show()
m = Male('Adam', 18, 65)
m.show
m.show()

내 이름은 Eve, 16살 이야.


<bound method Student.show of <__main__.Male object at 0x00000125ECBC8948>>

내 이름은 Adam, 18살 이야.


In [170]:
f.speak()
m.speak()

어머나 어머나
아이쿠 아이쿠


In [3]:
txt = '    필 땐 장미꽃처럼, 흩날릴 땐 벚꽃처럼, 질 땐 나팔꽃처럼'
txt2 = '아름다운 그 순간처럼, 어짜피 이것 밖에 난 못해'
txt3 = '너를 사랑하는 것 밖엔 못해'
type(txt)

str

In [6]:
txt.split() 
type(txt.split())

['필', '땐', '장미꽃처럼,', '흩날릴', '땐', '벚꽃처럼,', '질', '땐', '나팔꽃처럼']

list

In [9]:
'///'.join(txt.split(' '))

'/// /// /// /// 필/// 땐/// 장미꽃처럼,/// 흩날릴/// 땐/// 벚꽃처럼,/// 질/// 땐/// 나팔꽃처럼'

In [8]:
txt.strip()

'필 땐 장미꽃처럼, 흩날릴 땐 벚꽃처럼, 질 땐 나팔꽃처럼'

In [174]:
txt[0:10]
txt.find('장미')

'    필 땐 장미'

8

In [175]:
txt.replace('장미', '해바라기')

'    필 땐 해바라기꽃처럼, 흩날릴 땐 벚꽃처럼, 질 땐 나팔꽃처럼'

In [176]:
doc = pd.Series([txt, txt2, txt3], dtype="string")
doc = doc.to_frame()
doc

0
0      필 땐 장미꽃처럼, 흩날릴 땐 벚꽃처럼, 질 땐 나팔꽃처럼
1           아름다운 그 순간처럼, 어짜피 이것 밖에 난 못해
2                       너를 사랑하는 것 밖엔 못해

In [177]:
doc[0].str.contains('장미')

0     True
1    False
2    False
Name: 0, dtype: boolean

In [178]:
for choice in ['장미', '벚꽃', '사랑'] :
    doc[choice] = doc[0].str.contains(choice).fillna(0).astype(int)
doc

0  장미  벚꽃  사랑
0      필 땐 장미꽃처럼, 흩날릴 땐 벚꽃처럼, 질 땐 나팔꽃처럼   1   1   0
1           아름다운 그 순간처럼, 어짜피 이것 밖에 난 못해   0   0   0
2                       너를 사랑하는 것 밖엔 못해   0   0   1

In [179]:
doc1= ['사과', '오렌지', '수박']
doc2= ['토마토', '수박', '토마토']
doc3= ['사과', '토마토', '사과',]
df=pd.DataFrame(list(zip(doc1, doc2, doc3)))
df

0    1    2
0   사과  토마토   사과
1  오렌지   수박  토마토
2   수박  토마토   사과

In [180]:
choices = set(df[0].values) | (set(df[1].values)) | (set(df[2].values))
choices

{'사과', '수박', '오렌지', '토마토'}

In [181]:
df['all'] = df.apply(','.join, axis=1)
df

0    1    2         all
0   사과  토마토   사과   사과,토마토,사과
1  오렌지   수박  토마토  오렌지,수박,토마토
2   수박  토마토   사과   수박,토마토,사과

In [182]:
for choice in choices :
    df[choice] = df['all'].str.contains(choice)*1
df

0    1    2         all  오렌지  수박  토마토  사과
0   사과  토마토   사과   사과,토마토,사과    0   0    1   1
1  오렌지   수박  토마토  오렌지,수박,토마토    1   1    1   0
2   수박  토마토   사과   수박,토마토,사과    0   1    1   1

In [183]:
txt = '%    ?필 땐 /장미꽃:처럼!, 흩날릴\t 땐 !벚꽃처럼, $질 땐 나팔꽃처럼'
txt2 = '!아름다운 ?그 <순간처럼>, !어짜피 %이것 밖에 난 못해'
txt3 = '너를 %%사랑하는 것% 밖엔 못해'
doc = pd.Series([txt, txt2, txt3], dtype="string").to_frame()
doc

0
0  %    ?필 땐 /장미꽃:처럼!, 흩날릴	 땐 !벚꽃처럼, $질 땐 나팔꽃처럼
1             !아름다운 ?그 <순간처럼>, !어짜피 %이것 밖에 난 못해
2                            너를 %%사랑하는 것% 밖엔 못해

In [184]:
import re
p = re.compile('처럼')
print(p.findall(txt))

['처럼', '처럼', '처럼']


In [185]:
regex = ['[%]', '[?]', '[!]', '[/]', '[$]', '[>]', '[<]', '[:]', '\t']
def RegularClear(regex) :
    for pattern in regex :
        p = re.compile(pattern)
        doc[0] = doc[0].apply(lambda x : re.sub(p, '', str(x)))
    return doc[0]

In [186]:
RegularClear(regex)
doc

0        필 땐 장미꽃처럼, 흩날릴 땐 벚꽃처럼, 질 땐 나팔꽃처럼
1             아름다운 그 순간처럼, 어짜피 이것 밖에 난 못해
2                         너를 사랑하는 것 밖엔 못해
Name: 0, dtype: object

0
0      필 땐 장미꽃처럼, 흩날릴 땐 벚꽃처럼, 질 땐 나팔꽃처럼
1           아름다운 그 순간처럼, 어짜피 이것 밖에 난 못해
2                       너를 사랑하는 것 밖엔 못해

In [91]:
import os
os.makedirs('../data', exist_ok=True)
os.makedirs('../output', exist_ok=True)
os.makedirs('../image', exist_ok=True)